import Head from "next/head";
import { MDXRemote } from "next-mdx-remote";
import { serialize } from "next-mdx-remote/serialize";
import remarkMath from "remark-math";
import markdown from "remark-parse";
import rehypeKatex from "rehype-katex";
import rehypeHighlight from 'rehype-highlight'

const data = `# Testing KaTeX

This is the number $x = 13$ and this

$$
E = mc^2 + 2
$$

is an equation`;

export default function Home({ mdxSource }) {
  return (
    <div>
      <Head>
        <title>KaTeX test</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css"
          integrity="sha384-Um5gpz1odJg5Z4HAmzPtgZKdTBHZdw8S29IecapCSB31ligYPhHQZMIlWLYQGVoc"
          crossOrigin="anonymous"
        />
      </Head>

      <div>
        <span className="katex">
          <span className="katex-mathml">
            The KaTeX stylesheet is not loaded!
          </span>
          <span className="katex-version rule">KaTeX stylesheet version: </span>
        </span>

        <MDXRemote {...mdxSource} />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const mdxSource = await serialize(data, {
    mdxOptions: {
      remarkPlugins: [markdown, remarkMath],
      rehypePlugins: [rehypeKatex,rehypeHighlight]
    }
  });

  return {
    props: {
      mdxSource
    }
  };
}
